name: Terraform Apply

# on:
#   push:
#     branches:
#       - main 
# on:
#   workflow_dispatch:
#     inputs:
#       create:
#         description: 'Create resources'
#         required: true
on:
  workflow_dispatch:
    inputs:
       region:
        description: 'Deployment region'
        required: true
        default: 'ap-south-1'

env:
  AWS_REGION: ${{ inputs.region }}
  # AWS_REGION: ap-south-1

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
   
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{ inputs.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init
      working-directory: module/

    - name: Plan Terraform
      run: terraform plan -var-file=prerna.tfvars -out=tfplan
      working-directory: module/

    - name: Apply Terraform
      run: terraform apply -auto-approve "tfplan"
      working-directory: module/

