name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Deployment region'
        required: true
        default: 'ap-south-1a'

env:
  AWS_REGION: ${{ inputs.region }}
  
  
jobs:
  destroy:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
           aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      

    - name: Initialize Terraform
      working-directory: module/
      run: terraform init
      
      
    - name: Destroy Resources
      working-directory: module/
      run: terraform destroy -var-file=prerna.tfvars  -auto-approve 
      
